trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v1.*

pr: none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- script: |
    echo Hello
  displayName: Print hello
